openapi: 3.1.0
info:
  title: Chirpy API
  description: Simple, locally running Twitter-like API allowing "users" to post, view, and delete messages ("chirps").
  version: 1.0.0
paths:
  # Users
  /api/users:
    get:
      summary: Get all users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user_response'
    post:
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_request'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_response'
        '500':
          description: User not created
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                value: {"error": "Something went wrong"}
        '400':
          description: Missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                emptyStringPassword:
                  value: {"error": "Invalid Password"}
                missingEmail:
                  value: {"error": "Email required"}
                missingPassword:
                  value: {"error": "Password required"}
    put:
      summary: Update register user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_request'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_response'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                missingParameters:
                  value: {"error": "Something went wrong"}
                emailAlreadyExists:
                  value: {"error": "Something went wrong"}
components:
  schemas:
    user_response:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        is_chirpy_red:
          type: boolean
    user_request:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
          
